// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCanvFatmZBL5p6iPgW8XPDt91gCzmiHsg',
    appId: '1:488608797662:web:fe11fb9ee7ff87d36ec34f',
    messagingSenderId: '488608797662',
    projectId: 'sot-a677c',
    authDomain: 'sot-a677c.firebaseapp.com',
    databaseURL: 'https://sot-a677c.firebaseio.com',
    storageBucket: 'sot-a677c.appspot.com',
    measurementId: 'G-TRMW04KEJ7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_XCQYu8ycXUJR7GLAnXKgFLXnMYgRpi4',
    appId: '1:488608797662:android:38f8652457fdf6186ec34f',
    messagingSenderId: '488608797662',
    projectId: 'sot-a677c',
    databaseURL: 'https://sot-a677c.firebaseio.com',
    storageBucket: 'sot-a677c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKsfyy_8AhpRhK-oFB3a8vVSKuxs7t4LE',
    appId: '1:488608797662:ios:289e62e8213ce2376ec34f',
    messagingSenderId: '488608797662',
    projectId: 'sot-a677c',
    databaseURL: 'https://sot-a677c.firebaseio.com',
    storageBucket: 'sot-a677c.appspot.com',
    iosClientId:
        '488608797662-eolbn0p3hupq6s0arnq0t57hmn50v7mf.apps.googleusercontent.com',
    iosBundleId: 'com.example.sot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKsfyy_8AhpRhK-oFB3a8vVSKuxs7t4LE',
    appId: '1:488608797662:ios:289e62e8213ce2376ec34f',
    messagingSenderId: '488608797662',
    projectId: 'sot-a677c',
    databaseURL: 'https://sot-a677c.firebaseio.com',
    storageBucket: 'sot-a677c.appspot.com',
    iosClientId:
        '488608797662-eolbn0p3hupq6s0arnq0t57hmn50v7mf.apps.googleusercontent.com',
    iosBundleId: 'com.example.sot',
  );
}
